### ISSUE TITLE
Hello,this package contain server side?

### ISSUE THREAD

**Issue by moazzaq** [AndreSouzaAbreu/vue-data-table#57] opened 2022-03-23 12:56 UTC

**Comment by AndreSouzaAbreu** [comment] 2022-03-27 13:50
I didn't get it, sorry. Can you explain in details what you want?

**Comment by moazzaq** [comment] 2022-03-27 13:55
I mean, maybe I have 10,000 items in the table. I don't want it to be downloaded all at once.. I want when I choose the page number from the pagination, it returns the requested page to me. Your package is excellent and I apply it to my projects, but now I am working on a project that contains large data, as it loads all the data of the table

**Comment by AndreSouzaAbreu** [comment] 2022-03-27 17:03
Thanks for the clarification, I got it now.

I'd say this is a duplicate of [issue 40](https://github.com/AndreSouzaAbreu/vue-data-table/issues/40).

Currently, this plugin does not load data dynamically from the server.

I'm working to figure out what is the best approach to implement such functionality.

In the future, this plugin will be compatible with Laravel's Pagination API and
it will be possible to load data from the server on demand.

**Closed by AndreSouzaAbreu** 2022-03-27 17:03 UTC

**Comment by moazzaq** [comment] 2022-03-27 19:04
Thanks bro
